export const ABOUT = "ABOUT"
export const FORM_SUBMISSION_SUCCESS = "FORM_SUBMISSION_SUCCESS"
export const FORM_SUBMISSION_FAILED = "FORM_SUBMISSION_FAILED"
export const LOAD_CONTACTS = "LOAD_CONTACTS"
export const UPDATE_CONTACT_LIST = "UPDATE_CONTACT_LIST"


